export const HIDE_NEXT_ARROW = 'HIDE_NEXT_ARROW';
export const SHOW_NEXT_ARROW = 'SHOW_NEXT_ARROW';
export const SHOW_PREV_ARROW = 'SHOW_PREV_ARROW';
export const HIDE_PREV_ARROW = 'HIDE_PREV_ARROW';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_NUM_ITEMS_TO_SHOW = 'SET_NUM_ITEMS_TO_SHOW';
